---
   - name: Install mariadb package
     yum: name=mariadb-server,mariadb state=latest
    #sudo: yes
     when: ansible_os_family == "RedHat"

   - name: Install mariadb package
     apt: name=mariadb-server,mariadb state=latest
    #sudo: yes
     when: ansible_os_family == "Debian"

...
