---
   - name: Install php and extensions
     yum: name=php,php-mysqlnd,php-pdo,php-gd,php-snmp,php-mbstring,php-bcmath,php-ldap state=latest
#  sudo: yes
     when: ansible_os_family == "RedHat"


   - name: Install php and extensions
     apt: name=php,php-mysqlnd,php-pdo,php-gd,php-snmp,php-mbstring,php-bcmath,php-ldap state=latest
#  sudo: yes
     when: ansible_os_family == "Debian"


   - name: Creating phpinfo file
     shell: echo '<?php echo phpinfo(); ?>' > /var/www/html/info.php

#     notify:
 #      - restart httpd

#     handlers:
#       - name: restart httpd
#         service: name=httpd state=restarted

#       - name: restart mariadb
#         service: name=mariadb state=restarted



...
