---
   - name: Install httpd package
     yum: name=httpd state=latest
    #sudo: yes
     when: ansible_os_family == "RedHat"

   - name: Starting httpd service
     service: name=httpd state=started enabled=yes


   - name: Install apache2 package
     apt: name=apache2 state=latest
    #sudo: yes
     when: ansible_os_family == "Debian"

#   - name: Starting apache2 service
#     service: name=apache2 state=started enabled=yes


     notify:
        - restart httpd
#        - restart apache2




...
