---
   - name: Install httpd package
     yum: name=httpd state=latest
    #sudo: yes
     when: ansible_os_family == "RedHat"

   - name: Install apache2 package
     apt: name=apache2 state=latest
    #sudo: yes
     when: ansible_os_family == "Debian"

...
