---
    - name: mysql_secure_installation
      command: mysql_secure_installation
      

Create database/user.

# mysql -u root -p
# mariadb> create database racktables;
# mariadb> grant all privileges on racktables.* TO 'rackuser'@'localhost' identified by 'Passw0rd!';
# mariadb> flush privileges;
# mariadb> exit


   - name: Install httpd package
     yum: name=httpd state=latest
    #sudo: yes
     when: ansible_os_family == "RedHat"

   - name: Starting httpd service
     service: name=httpd state=started enabled=yes


   - name: Install apache2 package
     apt: name=apache2 state=latest
    #sudo: yes
     when: ansible_os_family == "Debian"

#   - name: Starting apache2 service
#     service: name=apache2 state=started enabled=yes


     notify:
        - restart httpd
#        - restart apache2

     handlers:
        - name: restart httpd
          service: name=httpd state=restarted


#     handlers:
#        - name: restart apache2
#          service: name=apache2 state=restarted


...
