---

     - name: Set root default password
       mysql_user:
         name: root
         password: martin**%%
         priv: '*.*:ALL,GRANT'
         state: present
         check_implicit_admin: yes
       ignore_errors: yes
       tags: mariadbrdf


     - name: Create a new database with name 'racktables5'
       mysql_db:
         name: racktables5
         login_user: root
         login_password: martin**%%
         state: present
       tags: mariadb

     - name: Create database user with name rackuser
       mysql_user:
         name: rackuser5
         login_user: root
         login_password: martin**%%
         password: 123456
         priv: 'racktables5.*:ALL'
         state: present
       tags: mariadbuser

     - name: Flushe database privileges
       mysql_user:
         name: root
         login_user: root
         login_password: martin**%%
         priv: '*.*:ALL,GRANT'
         state: present
         check_implicit_admin: yes
       ignore_errors: yes 
       tags: mariadbroot


#     - name: Testing createt user working
#       mysql_user:
#         login_user: rackuser5
#         login_password: 123456
#         state: present
#       tags: mariadbus


     # vars_prompt:
     #  - name: "Press Enter"
      #   prompt: "Enter"



...
