---
 - hosts: servers
   remote_user: root

   tasks:
     - include: tasks/install-apache.yml
     - include: tasks/install-mariadb.yml
     - include: tasks/install-mysqlpython.yml
     - include: tasks/mariadb.yml
#     - include: tasks/utf8-mysqlsrv.yml
     - include: tasks/utf8cnf.yml
     - meta: flush_handlers
     - include: tasks/install-phpex.yml
     - include: tasks/install-wget.yml


     - name: Create racktables user
       user: name=racktables shell=/sbin/nologin comment="RackTables User" createhome=yes home=/home/racktables


     - name: Download RackTables-0.20.14
       get_url: url=https://nchc.dl.sourceforge.net/project/racktables/RackTables-0.20.14.tar.gz dest=/tmp
       force: no  

     - name: Extract RackTables-0.20.14 archive
       command: chdir=/tmp /bin/tar xvf RackTables-0.20.14.tar.gz

     - name: Copy RackTables-0.20.14 wwwroot
       command: cp -rf /tmp/RackTables-0.20.14/wwwroot/ /var/www/html/racktables

     - name: Change ownership for copied catalog
       command: chown -R racktables:racktables /var/www/html/racktables

     - include: tasks/rackconf.yml
     - meta: flush_handlers

#     - include: tasks/secretphp.yml

     - file:
         path: /var/www/html/racktables/inc/secret.php
         owner: apache
         group: apache
         mode:  a=rw
         state: file
         state: touch 
       tags: file


     - name: RackTables installation step 4 of 7
       shell: yes '' | chmod 440 /var/www/html/racktables/inc/secret.php
       tags: chors

#       expect:
#          command:  chmod 440 /var/www/html/racktables/inc/secret.php
#          responses:
#            Question:
#                "Are you on this step": "Y"
                
#       tags: chors


     - name: Wait until the string Password is in the file secret.php before continuing
       wait_for:
         path: /var/www/html/racktables/inc/secret.php
         search_regex: username
       tags: wait


     - firewalld:
         service: http
         permanent: true
         state: enabled
       tags: firewall
       notify:
         - restart firewalld

   handlers:
     - name: restart httpd
       service: name=httpd state=restarted
    
     - name: restart mariadb
       service: name=mariadb state=restarted

     - name: restart firewalld
       service: name=firewalld state=restarted

...
